### ISSUE TITLE
大佬怎么联系？想和你聊聊FGO汉化的事儿

### ISSUE THREAD

**Issue by soulkey0117** [sunbqxyz/fgostory#1]

**Comment by sunbqxyz** [comment]
您好，直接通过issue联系我即可。您是nga之前发过贴的那位吗？我印象中看到过类似的帖子。
这个项目只是基于台湾的一个教程和现有资源的一个简单复现，我本人可能不具有您所期望的相关技术能力。同时由于文件检验机制、官方用户手册的约束，我也对直接通过修改文件实现日服汉化的可能性存有较大担忧。非常期待您对于相关工作的推进。
附上前文提到的台湾教程和现有资源，希望对您有所帮助：
台湾友人的教程：https://home.gamer.com.tw/creationDetail.php?sn=4893918
本站上的解密工具：https://github.com/nishuoshenme/FGOAssetsModifyTool

**Comment by soulkey0117** [comment]
是，我在NGA上发过我在做的汉化进度，看你这边文本进度已经完成4/5想联系你看看咱们的文本融合起来一起用，这样可以省掉很多无用功

**Comment by sunbqxyz** [comment]
嗯嗯，我在论坛里看到过您的帖子，非常有创造力的想法！
我提取的文本和简单处理过的内容都已经托管到这个仓库中，详细内容可以参考自述文件，您可以随便使用（不过由于是解包内容，实际上版权仍属于bilibili，我没有将其进行分发的权利，因此您对文本的正式使用可能还需要获得相关权利方的授权，这点还望您知悉）
另外根据千里眼，2.6的文本大约会在6月初实装，如果届时有时间，我大概会进行一个更新。

**Comment by soulkey0117** [comment]
好，谢谢哈
